# permissions for end users to view sidecarsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sidecarset-viewer-role
rules:
- apiGroups:
  - demo.ght.dev
  resources:
  - sidecarsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.ght.dev
  resources:
  - sidecarsets/status
  verbs:
  - get
